import { useEffect, useState } from "react";
import { api, ApiError } from "../api";
import type { AdminStats, AuditEntry, KnowledgeDocument, User } from "../types";

export function AdminPanel({ user }: { user: User }) {
  const [stats, setStats] = useState<AdminStats | null>(null);
  const [documents, setDocuments] = useState<KnowledgeDocument[]>([]);
  const [audit, setAudit] = useState<AuditEntry[]>([]);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  async function load() { try { const [s, d, a] = await Promise.all([api.adminStats(), api.documents(), api.audit()]); setStats(s); setDocuments(d.items); setAudit(a.items); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Admin data could not be loaded."); } }
  useEffect(() => { void load(); }, []);
  async function upload(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; const file = form.elements.namedItem("file") as HTMLInputElement; if (!file.files?.[0]) return; setBusy(true); setError(""); setMessage("");
    try { const result = await api.upload(file.files[0]); setMessage(`${result.message} ${result.document.title}`); form.reset(); await load(); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "The document could not be uploaded."); } finally { setBusy(false); }
  }
  async function reindex(id: string) { try { await api.reindex(id); setMessage("Document re-indexed successfully."); await load(); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Re-indexing failed."); } }
  async function remove(id: string) { if (!window.confirm("Delete this document and its indexed chunks?")) return; try { await api.deleteDocument(id); setMessage("Document deleted."); await load(); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Deletion failed."); } }
  return <main className="admin-layout"><aside className="admin-nav"><div className="eyebrow">ACME ADMIN</div><h1>Operations</h1><a href="#overview">Overview</a><a href="#documents">Knowledge base</a><a href="#audit">Audit log</a><div className="admin-identity">{user.display_name || user.email}<span>Administrator</span></div></aside><div className="admin-content"><section id="overview"><div className="section-title"><div><div className="eyebrow">SYSTEM OVERVIEW</div><h2>Support operations</h2></div><button className="button ghost" onClick={() => void load()}>Refresh</button></div>{error && <div className="form-alert error" role="alert">{error}</div>}{message && <div className="form-alert success" role="status">{message}</div>}<div className="stats-grid">{[["Documents", stats?.knowledge.documents], ["Indexed chunks", stats?.knowledge.chunks], ["Users", stats?.users], ["Conversations", stats?.conversations], ["Helpful votes", stats?.feedback_up], ["Feedback total", stats?.feedback_total]].map(([label, value]) => <div className="stat-card" key={String(label)}><span>{label}</span><strong>{value ?? "—"}</strong></div>)}</div></section><section id="documents"><div className="section-title"><div><div className="eyebrow">DOCUMENT MANAGEMENT</div><h2>Knowledge base</h2></div><form className="upload-form" onSubmit={upload}><label htmlFor="document-file" className="button ghost">Choose file</label><input id="document-file" name="file" type="file" accept=".txt,.md,.pdf" onChange={() => undefined} data-testid="document-upload" /><button className="button primary" disabled={busy}>{busy ? "Uploading…" : "Upload"}</button></form></div><p className="muted">Accepted: TXT, Markdown and PDF. Maximum 5 MB.</p><div className="table-wrap"><table><thead><tr><th>Document</th><th>Type</th><th>Status</th><th>Chunks</th><th>Actions</th></tr></thead><tbody>{documents.map((doc) => <tr key={doc.id}><td><strong>{doc.title}</strong><small>{doc.original_filename}</small>{doc.error_message && <small className="error-text">{doc.error_message}</small>}</td><td>{doc.content_type}</td><td><span className={`status ${doc.status}`}>{doc.status}</span></td><td>{doc.chunk_count}</td><td><button className="button ghost small" onClick={() => void reindex(doc.id)}>Re-index</button><button className="button danger small" onClick={() => void remove(doc.id)}>Delete</button></td></tr>)}</tbody></table></div></section><section id="audit"><div className="eyebrow">APPEND-ONLY ACTIVITY</div><h2>Audit log</h2><div className="audit-list">{audit.map((item) => <div className="audit-row" key={item.id}><span className="audit-action">{item.action}</span><span>{item.detail || `${item.target_type ?? "system"} ${item.target_id ?? ""}`}</span><time>{new Date(item.created_at).toLocaleString()}</time></div>)}</div></section></div></main>;
}
